{-# LANGUAGE TemplateHaskell #-}
module BenchTH where

import Language.Haskell.TH
import Language.Haskell.TH.Syntax

-- Generate 20 splices that each do reification
$(do info <- reify ''Int; pure [])
$(do info <- reify ''Bool; pure [])
$(do info <- reify ''Char; pure [])
$(do info <- reify ''Maybe; pure [])
$(do info <- reify ''Either; pure [])
$(do info <- reify ''IO; pure [])
$(do info <- reify ''String; pure [])
$(do info <- reify ''Show; pure [])
$(do info <- reify ''Eq; pure [])
$(do info <- reify ''Ord; pure [])
$(do info <- reify ''Read; pure [])
$(do info <- reify ''Num; pure [])
$(do info <- reify ''Functor; pure [])
$(do info <- reify ''Monad; pure [])
$(do info <- reify ''Applicative; pure [])
$(do info <- reify ''Traversable; pure [])
$(do info <- reify ''Foldable; pure [])
$(do info <- reify ''Semigroup; pure [])
$(do info <- reify ''Monoid; pure [])
$(do info <- reify ''Bounded; pure [])

-- 20 trivial splices (tests BCO caching)
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])
$(pure [])

-- 10 expression splices generating values
v1 :: Int; v1 = $(litE (integerL 1))
v2 :: Int; v2 = $(litE (integerL 2))
v3 :: Int; v3 = $(litE (integerL 3))
v4 :: Int; v4 = $(litE (integerL 4))
v5 :: Int; v5 = $(litE (integerL 5))
v6 :: Int; v6 = $(litE (integerL 6))
v7 :: Int; v7 = $(litE (integerL 7))
v8 :: Int; v8 = $(litE (integerL 8))
v9 :: Int; v9 = $(litE (integerL 9))
v10 :: Int; v10 = $(litE (integerL 10))
